// <auto-generated />
using System;
using LEGUZ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEGUZ.Migrations
{
    [DbContext(typeof(LeguzContext))]
    [Migration("20260514091921_AddAllEntities")]
    partial class AddAllEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LEGUZ.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SalespersonId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppUserId");

                    b.HasIndex("SalespersonId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            CreatedAt = new DateTime(2026, 5, 14, 4, 19, 16, 200, DateTimeKind.Local).AddTicks(4037),
                            FullName = "Administrador",
                            IsActive = true,
                            PasswordHash = "$2a$11$dGaPh6X3Ixn75yBPhKC1g.x1CDeNEZI.jlYQbQ1aHe6/y7UDKsjCG",
                            Role = "ADMIN",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.CreditNote", b =>
                {
                    b.Property<int>("CreditNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditNoteId"));

                    b.Property<decimal>("Chips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Crackling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DeliveryRouteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Dough")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FolioNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsBarbacoa")
                        .HasColumnType("bit");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Packages")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalespersonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoreName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Taco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CreditNoteId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryRouteId");

                    b.HasIndex("SalespersonId");

                    b.ToTable("CreditNotes");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("DeliveryRouteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.HasIndex("DeliveryRouteId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DailyDeposit", b =>
                {
                    b.Property<int>("DailyDepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyDepositId"));

                    b.Property<decimal>("BallconesInvoices")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BallconesSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CardPayments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CumbresInvoices")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CumbresSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomerInvoices")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Difference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaseoInvoices")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PaseoSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalToDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DailyDepositId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyDeposits");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DailyRouteRecord", b =>
                {
                    b.Property<int>("DailyRouteRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyRouteRecordId"));

                    b.Property<decimal>("ChipsReturned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChipsSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CracklingsSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DeliveryRouteId")
                        .HasColumnType("int");

                    b.Property<decimal>("DoughReturned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DoughSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KilosReturned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KilosSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadChips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadCrackling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadDough")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadHalfKilo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadHalfPackage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadHotKilos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadPackages")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadPresentation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadTacoKilo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadTacoPackage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PackagesReturned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PackagesSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalespersonId")
                        .HasColumnType("int");

                    b.Property<bool>("SalespersonSigned")
                        .HasColumnType("bit");

                    b.Property<decimal>("ShortageKilos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortagePackages")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TableChips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TableCrackling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TableDough")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TableHotKilos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TablePackages")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DailyRouteRecordId");

                    b.HasIndex("DeliveryRouteId");

                    b.HasIndex("SalespersonId");

                    b.HasIndex("Date", "DeliveryRouteId")
                        .IsUnique();

                    b.ToTable("DailyRouteRecords");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DailySalesRecord", b =>
                {
                    b.Property<int>("DailySalesRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailySalesRecordId"));

                    b.Property<decimal>("Bills")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashShortage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CheckPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Coins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DeliveryRouteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SalespersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSale")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DailySalesRecordId");

                    b.HasIndex("DeliveryRouteId");

                    b.HasIndex("SalespersonId");

                    b.HasIndex("Date", "DeliveryRouteId")
                        .IsUnique();

                    b.ToTable("DailySalesRecords");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DeliveryRoute", b =>
                {
                    b.Property<int>("DeliveryRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryRouteId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("DeliveryRouteId");

                    b.ToTable("DeliveryRoutes");

                    b.HasData(
                        new
                        {
                            DeliveryRouteId = 1,
                            IsActive = true,
                            Name = "BALCONES RIOS",
                            Number = 1
                        },
                        new
                        {
                            DeliveryRouteId = 2,
                            IsActive = true,
                            Name = "BALCONES LAGOS",
                            Number = 2
                        },
                        new
                        {
                            DeliveryRouteId = 3,
                            IsActive = true,
                            Name = "LA JOYA",
                            Number = 3
                        },
                        new
                        {
                            DeliveryRouteId = 4,
                            IsActive = true,
                            Name = "BUGAMBILIAS",
                            Number = 4
                        },
                        new
                        {
                            DeliveryRouteId = 5,
                            IsActive = true,
                            Name = "ALMAGUER",
                            Number = 5
                        },
                        new
                        {
                            DeliveryRouteId = 6,
                            IsActive = true,
                            Name = "LA JUAREZ",
                            Number = 6
                        },
                        new
                        {
                            DeliveryRouteId = 7,
                            IsActive = true,
                            Name = "PASEO RINCON",
                            Number = 7
                        },
                        new
                        {
                            DeliveryRouteId = 8,
                            IsActive = true,
                            Name = "VAMOS TAMAULIPAS",
                            Number = 8
                        },
                        new
                        {
                            DeliveryRouteId = 9,
                            IsActive = true,
                            Name = "RANCHO GRANDE",
                            Number = 9
                        },
                        new
                        {
                            DeliveryRouteId = 10,
                            IsActive = true,
                            Name = "PUERTA DEL SOL",
                            Number = 10
                        });
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Salesperson", b =>
                {
                    b.Property<int>("SalespersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalespersonId"));

                    b.Property<int?>("DeliveryRouteId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SalespersonId");

                    b.HasIndex("DeliveryRouteId");

                    b.ToTable("Salespersons");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.AppUser", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.Salesperson", "Salesperson")
                        .WithMany()
                        .HasForeignKey("SalespersonId");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.CreditNote", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("LEGUZ.Models.Entities.DeliveryRoute", "DeliveryRoute")
                        .WithMany()
                        .HasForeignKey("DeliveryRouteId");

                    b.HasOne("LEGUZ.Models.Entities.Salesperson", "Salesperson")
                        .WithMany()
                        .HasForeignKey("SalespersonId");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryRoute");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Customer", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.DeliveryRoute", "DeliveryRoute")
                        .WithMany()
                        .HasForeignKey("DeliveryRouteId");

                    b.Navigation("DeliveryRoute");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DailyRouteRecord", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.DeliveryRoute", "DeliveryRoute")
                        .WithMany()
                        .HasForeignKey("DeliveryRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LEGUZ.Models.Entities.Salesperson", "Salesperson")
                        .WithMany()
                        .HasForeignKey("SalespersonId");

                    b.Navigation("DeliveryRoute");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DailySalesRecord", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.DeliveryRoute", "DeliveryRoute")
                        .WithMany()
                        .HasForeignKey("DeliveryRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LEGUZ.Models.Entities.Salesperson", "Salesperson")
                        .WithMany()
                        .HasForeignKey("SalespersonId");

                    b.Navigation("DeliveryRoute");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Salesperson", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.DeliveryRoute", "DeliveryRoute")
                        .WithMany("Salespersons")
                        .HasForeignKey("DeliveryRouteId");

                    b.Navigation("DeliveryRoute");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DeliveryRoute", b =>
                {
                    b.Navigation("Salespersons");
                });
#pragma warning restore 612, 618
        }
    }
}
