// <auto-generated />
using System;
using LEGUZ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEGUZ.Migrations
{
    [DbContext(typeof(LeguzContext))]
    [Migration("20260514091021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LEGUZ.Models.Entities.DeliveryRoute", b =>
                {
                    b.Property<int>("DeliveryRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryRouteId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("DeliveryRouteId");

                    b.ToTable("DeliveryRoutes");

                    b.HasData(
                        new
                        {
                            DeliveryRouteId = 1,
                            IsActive = true,
                            Name = "BALCONES RIOS",
                            Number = 1
                        },
                        new
                        {
                            DeliveryRouteId = 2,
                            IsActive = true,
                            Name = "BALCONES LAGOS",
                            Number = 2
                        },
                        new
                        {
                            DeliveryRouteId = 3,
                            IsActive = true,
                            Name = "LA JOYA",
                            Number = 3
                        },
                        new
                        {
                            DeliveryRouteId = 4,
                            IsActive = true,
                            Name = "BUGAMBILIAS",
                            Number = 4
                        },
                        new
                        {
                            DeliveryRouteId = 5,
                            IsActive = true,
                            Name = "ALMAGUER",
                            Number = 5
                        },
                        new
                        {
                            DeliveryRouteId = 6,
                            IsActive = true,
                            Name = "LA JUAREZ",
                            Number = 6
                        },
                        new
                        {
                            DeliveryRouteId = 7,
                            IsActive = true,
                            Name = "PASEO RINCON",
                            Number = 7
                        },
                        new
                        {
                            DeliveryRouteId = 8,
                            IsActive = true,
                            Name = "VAMOS TAMAULIPAS",
                            Number = 8
                        },
                        new
                        {
                            DeliveryRouteId = 9,
                            IsActive = true,
                            Name = "RANCHO GRANDE",
                            Number = 9
                        },
                        new
                        {
                            DeliveryRouteId = 10,
                            IsActive = true,
                            Name = "PUERTA DEL SOL",
                            Number = 10
                        });
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Salesperson", b =>
                {
                    b.Property<int>("SalespersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalespersonId"));

                    b.Property<int?>("DeliveryRouteId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SalespersonId");

                    b.HasIndex("DeliveryRouteId");

                    b.ToTable("Salespersons");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.Salesperson", b =>
                {
                    b.HasOne("LEGUZ.Models.Entities.DeliveryRoute", "DeliveryRoute")
                        .WithMany("Salespersons")
                        .HasForeignKey("DeliveryRouteId");

                    b.Navigation("DeliveryRoute");
                });

            modelBuilder.Entity("LEGUZ.Models.Entities.DeliveryRoute", b =>
                {
                    b.Navigation("Salespersons");
                });
#pragma warning restore 612, 618
        }
    }
}
